server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name curtain.local curtain localhost _;
    include /etc/nginx/snippets/curtain-ssl.conf;
    client_max_body_size 2G;
    root /opt/curtain/curtain;
    charset utf-8;
    gzip on;
    gzip_vary on;
    gzip_types text/css application/javascript text/javascript application/json image/svg+xml;

    location = / { try_files /index.html =404; }

    location /admin {
        proxy_pass http://curtain_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept-Encoding "";
        sub_filter 'href="static/' 'href="/static/';
        sub_filter 'src="static/'  'src="/static/';
        sub_filter_once off;
    }

    location /ws/ {
        proxy_pass http://curtain_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400s;
    }

    location /static/ { alias /opt/curtain/backend/staticfiles/; expires 7d; }

    location /media/ { alias /opt/curtain/curtain/media/; }

    location / {
        proxy_pass http://curtain_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }
}
