# Generated by Django 4.2.7 on 2023-11-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curtain',
            name='md5',
        ),
        migrations.CreateModel(
            name='DataHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hash', models.TextField()),
                ('curtain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_hash', to='curtain.curtain')),
            ],
        ),
        migrations.CreateModel(
            name='DataAESEncryptionFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('encrypted_decryption_key', models.TextField()),
                ('encrypted_iv', models.TextField()),
                ('curtain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encryption_factors', to='curtain.curtain')),
            ],
        ),
    ]
