# Generated by Django 4.2.13 on 2024-06-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0004_lastaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtain',
            name='permanent',
            field=models.BooleanField(default=True),
        ),
    ]
