# Generated by Django 5.1.2 on 2024-11-17 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0005_curtain_permanent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('curtain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_cite', to='curtain.curtain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_cite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
