# Generated by Django 5.1.3 on 2024-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0006_datacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacite',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='datacite',
            name='form_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datacite',
            name='pii_statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
