# Generated by Django 5.1.4 on 2024-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0007_datacite_contact_email_datacite_form_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacite',
            name='curtain',
        ),
        migrations.AlterField(
            model_name='datacite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
