# Generated by Django 5.1.4 on 2024-12-11 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0009_datacite_curtain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacite',
            name='curtain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_cite', to='curtain.curtain'),
        ),
    ]
