# Generated by Django 5.2.8 on 2025-11-18 13:54

import curtain.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0012_alter_datacite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacite',
            name='local_file',
            field=models.FileField(blank=True, help_text='Local file storage for DataCite data (stored on host, not cloud)', null=True, storage=curtain.storage.DataCiteLocalStorage, upload_to='datacite_files/'),
        ),
    ]
