# Generated by Django 5.2.8 on 2025-11-19 17:05

import curtain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0013_add_datacite_local_file_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtain',
            name='expiry_duration',
            field=models.DurationField(default=curtain.models.get_default_expiry_duration),
        ),
    ]
