# Generated by Django 5.2.8 on 2025-11-19 21:10

import django.db.models.deletion
import drf_chunked_upload.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0014_add_curtain_expiry_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtainChunkedUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, null=True, upload_to=drf_chunked_upload.models.generate_filename)),
                ('filename', models.CharField(max_length=255)),
                ('offset', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Incomplete'), (2, 'Complete')], default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename as provided by client', max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, help_text='Detected MIME type of the uploaded file', max_length=100, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Total size of the uploaded file in bytes', null=True)),
                ('upload_session_id', models.CharField(blank=True, help_text='Session ID for tracking related uploads', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curtain_chunked_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
