# Generated by Django 5.2.8 on 2025-11-20 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0015_curtainchunkedupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='When to start showing this announcement', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When to stop showing this announcement', null=True)),
                ('show_on_login', models.BooleanField(default=False, help_text='Show this announcement on login page')),
                ('dismissible', models.BooleanField(default=True, help_text='Can users dismiss this announcement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created'],
            },
        ),
    ]
