# Generated by Django 5.2.8 on 2025-11-20 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0016_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('permanent', 'Make Permanent'), ('extend', 'Extend Expiry Duration')], default='permanent', help_text='Type of request: permanent or extend', max_length=10)),
                ('requested_expiry_months', models.IntegerField(blank=True, help_text='Requested expiry duration in months (for extend requests)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True, help_text="User's reason for requesting permanent link or extension", null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's notes on the request", null=True)),
                ('curtain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_requests', to='curtain.curtain')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_link_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permanent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('curtain', 'requested_by', 'status')},
            },
        ),
    ]
