# Generated by Django 5.2.8 on 2025-11-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0018_curtaincollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacite',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Optional collection - if set, all curtain sessions in collection will be included as relatedIdentifiers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_cite', to='curtain.curtaincollection'),
        ),
    ]
