# Generated by Django 5.2.10 on 2026-01-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0019_datacite_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtaincollection',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
