# Generated by Django 5.2.8 on 2026-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtain', '0020_curtaincollection_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtain',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
